# Generated by Django 4.2.16 on 2025-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='media/backgrounds/'),
        ),
    ]
