# Generated by Django 4.2.16 on 2025-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_bio_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('github', 'fab fa-github'), ('instagram', 'fab fa-instagram'), ('facebook', 'fab fa-facebook'), ('twitter', 'fab fa-twitter'), ('linkedin', 'fab fa-linkedin'), ('youtube', 'fab fa-youtube'), ('spotify', 'fab fa-spotify'), ('telegram', 'fab fa-telegram'), ('tiktok', 'fab fa-tiktok'), ('twitch', 'fab fa-twitch'), ('discord', 'fab fa-discord'), ('reddit', 'fab fa-reddit'), ('pinterest', 'fab fa-pinterest'), ('soundcloud', 'fab fa-soundcloud'), ('applemusic', 'fab fa-applemusic'), ('bandcamp', 'fab fa-bandcamp')], max_length=255),
        ),
    ]
