# Generated by Django 4.2.16 on 2025-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='links',
            field=models.ManyToManyField(to='cabinet.link'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='playlist',
            field=models.ManyToManyField(to='cabinet.music'),
        ),
    ]
