# Generated by Django 4.2.16 on 2025-07-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_bio_links_alter_bio_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='links',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='playlist',
        ),
        migrations.AddField(
            model_name='bio',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.link'),
        ),
        migrations.AddField(
            model_name='bio',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.music'),
        ),
    ]
