# Generated by Django 4.2.16 on 2025-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_remove_bio_links_remove_bio_playlist_bio_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='links',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='playlist',
        ),
        migrations.AddField(
            model_name='bio',
            name='links',
            field=models.ManyToManyField(related_name='bio', to='cabinet.link'),
        ),
        migrations.AddField(
            model_name='bio',
            name='playlist',
            field=models.ManyToManyField(related_name='bio', to='cabinet.music'),
        ),
    ]
