# Generated by Django 4.2.16 on 2025-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_remove_bio_links_remove_bio_playlist_bio_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('github', 'fab fa-github'), ('gitlab', 'fab fa-gitlab'), ('instagram', 'fab fa-instagram'), ('facebook', 'fab fa-facebook-f'), ('twitter', 'fab fa-x-twitter'), ('linkedin', 'fab fa-linkedin-in'), ('youtube', 'fab fa-youtube'), ('spotify', 'fab fa-spotify'), ('telegram', 'fab fa-telegram'), ('tiktok', 'fab fa-tiktok'), ('twitch', 'fab fa-twitch'), ('discord', 'fab fa-discord'), ('reddit', 'fab fa-reddit-alien'), ('pinterest', 'fab fa-pinterest'), ('soundcloud', 'fab fa-soundcloud'), ('steam', 'fab fa-steam'), ('website', 'fas fa-globe'), ('email', 'fas fa-envelope'), ('phone', 'fas fa-phone')], max_length=255),
        ),
    ]
