# Generated by Django 4.2.16 on 2025-07-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_icon_link_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.link'),
        ),
    ]
